package petfinder.transferwise.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CATALOGUE".
*/
public class CatalogueDao extends AbstractDao<Catalogue, Long> {

    public static final String TABLENAME = "CATALOGUE";

    /**
     * Properties of entity Catalogue.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Breed = new Property(1, String.class, "breed", false, "BREED");
        public final static Property Animal = new Property(2, String.class, "animal", false, "ANIMAL");
    }

    private DaoSession daoSession;


    public CatalogueDao(DaoConfig config) {
        super(config);
    }
    
    public CatalogueDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CATALOGUE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BREED\" TEXT," + // 1: breed
                "\"ANIMAL\" TEXT);"); // 2: animal
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CATALOGUE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Catalogue entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String breed = entity.getBreed();
        if (breed != null) {
            stmt.bindString(2, breed);
        }
 
        String animal = entity.getAnimal();
        if (animal != null) {
            stmt.bindString(3, animal);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Catalogue entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String breed = entity.getBreed();
        if (breed != null) {
            stmt.bindString(2, breed);
        }
 
        String animal = entity.getAnimal();
        if (animal != null) {
            stmt.bindString(3, animal);
        }
    }

    @Override
    protected final void attachEntity(Catalogue entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Catalogue readEntity(Cursor cursor, int offset) {
        Catalogue entity = new Catalogue( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // breed
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // animal
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Catalogue entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBreed(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAnimal(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Catalogue entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Catalogue entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Catalogue entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
