package petfinder.transferwise.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PET__BREED".
*/
public class Pet_BreedDao extends AbstractDao<Pet_Breed, Long> {

    public static final String TABLENAME = "PET__BREED";

    /**
     * Properties of entity Pet_Breed.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Pet_id = new Property(1, Integer.class, "pet_id", false, "PET_ID");
        public final static Property Breed = new Property(2, String.class, "breed", false, "BREED");
    }

    private DaoSession daoSession;


    public Pet_BreedDao(DaoConfig config) {
        super(config);
    }
    
    public Pet_BreedDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PET__BREED\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PET_ID\" INTEGER," + // 1: pet_id
                "\"BREED\" TEXT);"); // 2: breed
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PET__BREED\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Pet_Breed entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer pet_id = entity.getPet_id();
        if (pet_id != null) {
            stmt.bindLong(2, pet_id);
        }
 
        String breed = entity.getBreed();
        if (breed != null) {
            stmt.bindString(3, breed);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Pet_Breed entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer pet_id = entity.getPet_id();
        if (pet_id != null) {
            stmt.bindLong(2, pet_id);
        }
 
        String breed = entity.getBreed();
        if (breed != null) {
            stmt.bindString(3, breed);
        }
    }

    @Override
    protected final void attachEntity(Pet_Breed entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Pet_Breed readEntity(Cursor cursor, int offset) {
        Pet_Breed entity = new Pet_Breed( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // pet_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // breed
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Pet_Breed entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPet_id(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setBreed(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Pet_Breed entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Pet_Breed entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Pet_Breed entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
